version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  node: circleci/node@4.1.0
jobs:
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install
      - node/install-yarn
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: TypeScript build
      - cypress/run
workflows:
  node-tests:
    jobs:
      - test
