version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  test:
    docker:
      - image: cypress/base:10
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - node/install
      - node/install-yarn
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: TypeScript build
      - run:
          command: yarn test
          name: Run tests
workflows:
  node-tests:
    jobs:
      - test
