version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          start: npm start
          wait-on: 'http://localhost:$CYPRESS_TEST_APP_PORT'
