version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  test:
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: TypeScript build
      - run:
          command: yarn test
          name: Run YARN tests
workflows:
  node-tests:
    jobs:
      - test
