version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node12.6.0-chrome77'
workflows:
  build:
    jobs:
      - cypress/install:
          build: yarn build
      - cypress/run:
          record: false
          yarn: true
          executor: with-chrome
          browser: chrome
          start: npm start
          wait-on: 'http://localhost:$CYPRESS_TEST_APP_PORT'
